config/routes.rb
Rails.application.routes.draw do

  devise_for :users
root to: "home#index"

resources :articles do
  resources :comments, only: [:create]
end

resource :contacts, only: [:new, :create], path_names: {:new => ''}

get 'terms' => 'pages#terms'
get 'about' => 'pages#about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  has_many :comments

  def subject
    title
  end
  def comment_last
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_filter :authenticate_user!, :only => [:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.author = current_user.username
       @article.save
       redirect_to @article
    else
      render action: 'new'
    end

  end

  def edit
      @article = Article.find(params[:id])
    if current_user.username == @article.author

    else
      redirect_to articles_path
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
       redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
        @article = Article.find(params[:id])
        if current_user.username == @article.author
          @article.destroy
          redirect_to articles_path
        else
          redirect_to articles_path
        end
  end

  private

  def article_params
      params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @comments = @article.comments.new(comment_params)
    @comments.author = current_user.username
    @comments.save

    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new

  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
       @contact.save
    else
      render action: 'new'
    end

  end

  private

  def contact_params
      params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def terms
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<p> thanks </p>

app/views/articles/destroy.html.erb
<h2> article deleted </h2>

app/views/articles/edit.html.erb
<h1> Edit article </h1>


<%=  form_for :article, url: article_path(@article), method: :put do |f| %>
<% if @article && @article.errors.any? %>
<%= @article.errors.full_messages %>
<% end %>
<p>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %> <br>
  <%= f.text_area :text %>
</p>
<p> <%= f.submit %>
</p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>

<h2>
  <%= article.title %>
</h2>
<p>
  <%= article.text %>
</p>
<%= link_to 'show', article_path(article) %> |
<%= link_to 'edit', edit_article_path(article) %> |
<%= link_to 'delete', article, method: :delete, data: {confirm: 'Вы уверены?'} %>
<hr>
<% end %>

app/views/articles/new.html.erb
<h1> New article </h1>


<%=  form_for :article, url: articles_path do |f| %>
<% if @article && @article.errors.any? %>
<%= @article.errors.full_messages %>
<% end %>
<p>
  <%= f.label :title %> <br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %> <br>
  <%= f.text_area :text %>
</p>
<p> <%= f.submit %>
</p>
<% end %>

app/views/articles/show.html.erb
  <h4> <%= @article.title %> </h4>
  <p>
    <%= @article.text %>
  </p>
<h3> Комментарии </h3>
<% @article.comments.each do |comment| %>

<h4>
  <%= comment.author %>
</h4>
<p>
  <%= comment.body %>
<hr>
<% end %>
<p>
 <%= form_for ([@article, @article.comments.build]) do |f| %>
</p>
<p>
  <%= f.label :body %> <br>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>

</p>

<% end %>

app/views/contacts/create.html.erb
<p> thanks </p>

app/views/contacts/new.html.erb
<h1>Оставьте email и свое сообщение</h1>

<%= form_for :contact, url: contacts_path do |f| %>

  <p>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.text_field :message %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/home/index.html.erb
<p> <%= link_to 'Articles', articles_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="\">Blog</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'New article', new_article_path %></li>
              <li><%= link_to 'About', about_path %></li>
              <li><%= link_to 'Terms', terms_path %></li>
              <li><%= link_to 'Contacts', contacts_path %></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                       <% if user_signed_in? %>
              <li>
                    <a href="#">
                       Hello, <%= current_user.username %>
                     </a>
                  </li>
              <li>
                    <%= link_to 'sign out', destroy_user_session_path, method: :delete %>
                  <% else %>
                </li> <li> <%= link_to 'sign in', new_user_session_path %>
                  <% end %>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">



          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>
        </div>
        <div class="col-md-2"></div>
      </div>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h2> О нас </h2>

app/views/pages/terms.html.erb
<h2> условия использования </h2>